// Cricsheet has no handedness or bowling-style fields, so these are curated by Cricsheet display name.
// Format: '<bat hand> <bowl type>' - RF/LF right/left pace, OB off-break, LB leg-break, SLA left-arm orthodox, LWS left-arm wrist.
export const playerStyles = {
  'A Badoni': 'R OB',
  'A Kumble': 'R LB',
  'A Mishra': 'R LB',
  'A Nehra': 'L LF',
  'A Nortje': 'R RF',
  'A Symonds': 'R OB',
  'AB Agarkar': 'R RF',
  'AB de Villiers': 'R',
  'AB Dinda': 'R RF',
  'AC Gilchrist': 'L',
  'AD Mathews': 'R RF',
  'AD Russell': 'R RF',
  'AF Milne': 'R RF',
  'AJ Finch': 'R',
  'AJ Tye': 'R RF',
  'AL Phehlukwayo': 'R RF',
  'AM Rahane': 'R',
  'AR Patel': 'L SLA',
  'AT Carey': 'L',
  'AT Rayudu': 'R',
  'AU Rashid': 'R LB',
  'Abhishek Porel': 'L',
  'Abhishek Sharma': 'L SLA',
  'Akash Deep': 'R RF',
  'Anrich Nortje': 'R RF',
  'Anmolpreet Singh': 'R',
  'Arshdeep Singh': 'L LF',
  'Avesh Khan': 'R RF',
  'B Kumar': 'R RF',
  'B Lee': 'R RF',
  'B Sai Sudharsan': 'L',
  'BA Stokes': 'L RF',
  'BB McCullum': 'R',
  'BJ Hodge': 'R',
  'BKG Mendis': 'R',
  'Basil Thampi': 'R RF',
  'C Munro': 'L',
  'CA Lynn': 'R',
  'CH Gayle': 'L OB',
  'CH Morris': 'R RF',
  'CJ Jordan': 'R RF',
  'CL White': 'R LB',
  'CR Woakes': 'R RF',
  'CV Varun': 'R OB',
  'Chetan Sakariya': 'L LF',
  'D Padikkal': 'L',
  'DA Miller': 'L',
  'DA Warner': 'L',
  'DE Bollinger': 'L LF',
  'DJ Bravo': 'R RF',
  'DJ Hooda': 'R OB',
  'DJ Hussey': 'R OB',
  'DJ Mitchell': 'R RF',
  'DJ Willey': 'L LF',
  'DJG Sammy': 'R RF',
  'DL Chahar': 'R RF',
  'DL Vettori': 'L SLA',
  'DM Bravo': 'L',
  'DM de Silva': 'R OB',
  'DPMD Jayawardene': 'R',
  'DR Smith': 'R RF',
  'DT Christian': 'R RF',
  'DW Steyn': 'R RF',
  'Dhruv Jurel': 'R',
  'EJG Morgan': 'L',
  'F Behardien': 'R',
  'F du Plessis': 'R',
  'FA Allen': 'L',
  'Fazalhaq Farooqi': 'L LF',
  'G Gambhir': 'L',
  'GC Smith': 'L',
  'GD Phillips': 'R OB',
  'GJ Bailey': 'R',
  'GJ Maxwell': 'R OB',
  'Gulbadin Naib': 'R RF',
  'H Klaasen': 'R',
  'HC Brook': 'R',
  'HH Pandya': 'R RF',
  'HM Amla': 'R',
  'HV Patel': 'R RF',
  'Harbhajan Singh': 'R OB',
  'Harpreet Brar': 'L SLA',
  'I Sharma': 'R RF',
  'I Tahir': 'R LB',
  'I Udana': 'L LF',
  'IK Pathan': 'L LF',
  'IS Sodhi': 'R LB',
  'Ishan Kishan': 'L',
  'J Botha': 'R OB',
  'J Charles': 'R',
  'JA Morkel': 'L RF',
  'JC Archer': 'R RF',
  'JC Buttler': 'R',
  'JD Unadkat': 'L LF',
  'JDS Neesham': 'L RF',
  'JE Root': 'R OB',
  'JEC Franklin': 'L LF',
  'JH Kallis': 'R RF',
  'JJ Bumrah': 'R RF',
  'JM Bairstow': 'R',
  'JO Holder': 'R RF',
  'JP Duminy': 'L SLA',
  'JP Inglis': 'R',
  'JR Hazlewood': 'R RF',
  'JR Philippe': 'R',
  'Jitesh Sharma': 'R',
  'K Gowtham': 'R OB',
  'K Rabada': 'R RF',
  'KA Pollard': 'R RF',
  'KC Sangakkara': 'L',
  'KD Karthik': 'R',
  'KD Mills': 'R RF',
  'KH Pandya': 'L SLA',
  'KL Rahul': 'R',
  'KOA Powell': 'L',
  'KS Williamson': 'R OB',
  'KW Richardson': 'R RF',
  'Karn Sharma': 'R LB',
  'Khaleel Ahmed': 'L LF',
  'Kuldeep Yadav': 'L LWS',
  'L Balaji': 'R RF',
  'L Ngidi': 'R RF',
  'LH Ferguson': 'R RF',
  'LMP Simmons': 'R RF',
  'LR Shukla': 'R RF',
  'LS Livingstone': 'R LB',
  'M Jansen': 'L LF',
  'M Kartik': 'L SLA',
  'M Morkel': 'R RF',
  'M Muralitharan': 'R OB',
  'M Pathirana': 'R RF',
  'M Vijay': 'R OB',
  'MA Starc': 'L LF',
  'MEK Hussey': 'L',
  'MG Johnson': 'L LF',
  'MJ Guptill': 'R',
  'MJ Santner': 'L SLA',
  'MK Pandey': 'R',
  'ML Hayden': 'L',
  'MM Ali': 'R OB',
  'MM Patel': 'R RF',
  'MM Sharma': 'R RF',
  'MN Samuels': 'R OB',
  'MP Stoinis': 'R RF',
  'MP Yadav': 'R RF',
  'MR Marsh': 'R RF',
  'MS Dhoni': 'R',
  'MS Wade': 'L',
  'MV Boucher': 'R',
  'Mayank Agarwal': 'R',
  'Mayank Markande': 'R LB',
  'Mohammad Nabi': 'R OB',
  'Mohammed Shami': 'R RF',
  'Mohammed Siraj': 'R RF',
  'Mohsin Khan': 'L LF',
  'Mujeeb Ur Rahman': 'R OB',
  'Mukesh Kumar': 'R RF',
  'Murugan Ashwin': 'R LB',
  'N Pooran': 'L',
  'N Rana': 'L OB',
  'NLTC Perera': 'L RF',
  'NM Lyon': 'R OB',
  'NT Ellis': 'R RF',
  'Naveen-ul-Haq': 'R RF',
  'Navdeep Saini': 'R RF',
  'Noor Ahmad': 'L LWS',
  'P Kumar': 'R RF',
  'PA Patel': 'L',
  'PD Salt': 'R',
  'PJ Cummins': 'R RF',
  'PP Chawla': 'R LB',
  'PP Ojha': 'L SLA',
  'PVD Chameera': 'R RF',
  'Pawan Negi': 'L SLA',
  'Prasidh Krishna': 'R RF',
  'Prithvi Shaw': 'R',
  'Q de Kock': 'L',
  'R Ashwin': 'R OB',
  'R Dravid': 'R',
  'R Parag': 'R LB',
  'R Sai Kishore': 'L SLA',
  'R Tewatia': 'L LB',
  'R Vinay Kumar': 'R RF',
  'RA Jadeja': 'L SLA',
  'RD Chahar': 'R LB',
  'RD Gaikwad': 'R',
  'RE van der Merwe': 'L SLA',
  'RG Sharma': 'R',
  'RJW Topley': 'L LF',
  'RL Chase': 'R OB',
  'RP Singh': 'L LF',
  'RR Pant': 'L',
  'RR Rossouw': 'L',
  'RT Ponting': 'R',
  'RV Uthappa': 'R',
  'Rachin Ravindra': 'L SLA',
  'Rahul Chahar': 'R LB',
  'Rajat Patidar': 'R',
  'Rashid Khan': 'R LB',
  'Ravi Bishnoi': 'R LB',
  'Rinku Singh': 'L',
  'S Badree': 'R LB',
  'S Badrinath': 'R',
  'S Dhawan': 'L',
  'S Sreesanth': 'R RF',
  'SA Abbott': 'R RF',
  'SA Yadav': 'R',
  'SC Ganguly': 'L RF',
  'SE Marsh': 'L',
  'SK Raina': 'L OB',
  'SL Malinga': 'R RF',
  'SM Curran': 'L LF',
  'SMSM Senanayake': 'R OB',
  'SO Hetmyer': 'L',
  'SP Narine': 'L OB',
  'SPD Smith': 'R LB',
  'SR Tendulkar': 'R',
  'SR Watson': 'R RF',
  'SS Iyer': 'R',
  'SS Tiwary': 'R',
  'SV Samson': 'R',
  'SW Billings': 'R',
  'Sandeep Sharma': 'R RF',
  'Sarfaraz Khan': 'R',
  'Shahbaz Ahmed': 'L SLA',
  'Shardul Thakur': 'R RF',
  'Shreyas Gopal': 'R LB',
  'Shubman Gill': 'R',
  'Simarjeet Singh': 'R RF',
  'Suyash Sharma': 'R LWS',
  'T Natarajan': 'L LF',
  'T Shamsi': 'L LWS',
  'T Stubbs': 'R',
  'TA Boult': 'L LF',
  'TD Paine': 'R',
  'TG Southee': 'R RF',
  'TK Curran': 'R RF',
  'TM Dilshan': 'R OB',
  'TM Head': 'L OB',
  'TWM Latham': 'L',
  'Tilak Varma': 'L OB',
  'Tushar Deshpande': 'R RF',
  'UT Yadav': 'R RF',
  'V Kohli': 'R RF',
  'V Sehwag': 'R OB',
  'V Shankar': 'R RF',
  'VR Iyer': 'L RF',
  'W Hasaranga': 'R LB',
  'WD Parnell': 'L LF',
  'WG Jacks': 'R OB',
  'WP Saha': 'R',
  'Washington Sundar': 'R OB',
  'Y Chahal': 'R LB',
  'YK Pathan': 'R OB',
  'YS Chahal': 'R LB',
  'Yash Dayal': 'L LF',
  'Yashasvi Jaiswal': 'L',
  'Yuvraj Singh': 'L SLA',
  'Z Khan': 'L LF',
}