// Nationality by Cricsheet display name; anyone absent defaults to India, since the uncapped IPL long tail is overwhelmingly Indian.
export const playerCountries = {
  'A Badoni': 'India',
  'A Kumble': 'India',
  'A Mishra': 'India',
  'A Nehra': 'India',
  'A Nortje': 'South Africa',
  'A Symonds': 'Australia',
  'AB Agarkar': 'India',
  'AB de Villiers': 'South Africa',
  'AB Dinda': 'India',
  'AC Gilchrist': 'Australia',
  'AD Mathews': 'Sri Lanka',
  'AD Russell': 'West Indies',
  'AF Milne': 'New Zealand',
  'AJ Finch': 'Australia',
  'AJ Tye': 'Australia',
  'AL Phehlukwayo': 'South Africa',
  'AM Rahane': 'India',
  'AR Patel': 'India',
  'AT Carey': 'Australia',
  'AT Rayudu': 'India',
  'AU Rashid': 'England',
  'Abhishek Porel': 'India',
  'Abhishek Sharma': 'India',
  'Akash Deep': 'India',
  'Anrich Nortje': 'South Africa',
  'Anmolpreet Singh': 'India',
  'Arshdeep Singh': 'India',
  'Avesh Khan': 'India',
  'B Kumar': 'India',
  'B Lee': 'Australia',
  'B Sai Sudharsan': 'India',
  'BA Stokes': 'England',
  'BB McCullum': 'New Zealand',
  'BJ Hodge': 'Australia',
  'BKG Mendis': 'Sri Lanka',
  'Basil Thampi': 'India',
  'C Munro': 'New Zealand',
  'CA Lynn': 'Australia',
  'CH Gayle': 'West Indies',
  'CH Morris': 'South Africa',
  'CJ Jordan': 'England',
  'CL White': 'Australia',
  'CR Woakes': 'England',
  'CV Varun': 'India',
  'Chetan Sakariya': 'India',
  'D Padikkal': 'India',
  'DA Miller': 'South Africa',
  'DA Warner': 'Australia',
  'DE Bollinger': 'Australia',
  'DJ Bravo': 'West Indies',
  'DJ Hooda': 'India',
  'DJ Hussey': 'Australia',
  'DJ Mitchell': 'New Zealand',
  'DJ Willey': 'England',
  'DJG Sammy': 'West Indies',
  'DL Chahar': 'India',
  'DL Vettori': 'New Zealand',
  'DM Bravo': 'West Indies',
  'DM de Silva': 'Sri Lanka',
  'DPMD Jayawardene': 'Sri Lanka',
  'DR Smith': 'West Indies',
  'DT Christian': 'Australia',
  'DW Steyn': 'South Africa',
  'Dhruv Jurel': 'India',
  'EJG Morgan': 'England',
  'F Behardien': 'South Africa',
  'F du Plessis': 'South Africa',
  'FA Allen': 'West Indies',
  'Fazalhaq Farooqi': 'Afghanistan',
  'G Gambhir': 'India',
  'GC Smith': 'South Africa',
  'GD Phillips': 'New Zealand',
  'GJ Bailey': 'Australia',
  'GJ Maxwell': 'Australia',
  'Gulbadin Naib': 'Afghanistan',
  'H Klaasen': 'South Africa',
  'HC Brook': 'England',
  'HH Pandya': 'India',
  'HM Amla': 'South Africa',
  'HV Patel': 'India',
  'Harbhajan Singh': 'India',
  'Harpreet Brar': 'India',
  'I Sharma': 'India',
  'I Tahir': 'South Africa',
  'I Udana': 'Sri Lanka',
  'IK Pathan': 'India',
  'IS Sodhi': 'New Zealand',
  'Ishan Kishan': 'India',
  'J Botha': 'South Africa',
  'J Charles': 'West Indies',
  'JA Morkel': 'South Africa',
  'JC Archer': 'England',
  'JC Buttler': 'England',
  'JD Unadkat': 'India',
  'JDS Neesham': 'New Zealand',
  'JE Root': 'England',
  'JEC Franklin': 'New Zealand',
  'JH Kallis': 'South Africa',
  'JJ Bumrah': 'India',
  'JM Bairstow': 'England',
  'JO Holder': 'West Indies',
  'JP Duminy': 'South Africa',
  'JP Inglis': 'Australia',
  'JR Hazlewood': 'Australia',
  'JR Philippe': 'Australia',
  'Jitesh Sharma': 'India',
  'K Gowtham': 'India',
  'K Rabada': 'South Africa',
  'KA Pollard': 'West Indies',
  'KC Sangakkara': 'Sri Lanka',
  'KD Karthik': 'India',
  'KD Mills': 'New Zealand',
  'KH Pandya': 'India',
  'KL Rahul': 'India',
  'KOA Powell': 'West Indies',
  'KS Williamson': 'New Zealand',
  'KW Richardson': 'Australia',
  'Karn Sharma': 'India',
  'Khaleel Ahmed': 'India',
  'Kuldeep Yadav': 'India',
  'L Balaji': 'India',
  'L Ngidi': 'South Africa',
  'LH Ferguson': 'New Zealand',
  'LMP Simmons': 'West Indies',
  'LR Shukla': 'India',
  'LS Livingstone': 'England',
  'M Jansen': 'South Africa',
  'M Kartik': 'India',
  'M Morkel': 'South Africa',
  'M Muralitharan': 'Sri Lanka',
  'M Pathirana': 'Sri Lanka',
  'M Vijay': 'India',
  'MA Starc': 'Australia',
  'MEK Hussey': 'Australia',
  'MG Johnson': 'Australia',
  'MJ Guptill': 'New Zealand',
  'MJ Santner': 'New Zealand',
  'MK Pandey': 'India',
  'ML Hayden': 'Australia',
  'MM Ali': 'England',
  'MM Patel': 'India',
  'MM Sharma': 'India',
  'MN Samuels': 'West Indies',
  'MP Stoinis': 'Australia',
  'MP Yadav': 'India',
  'MR Marsh': 'Australia',
  'MS Dhoni': 'India',
  'MS Wade': 'Australia',
  'MV Boucher': 'South Africa',
  'Mayank Agarwal': 'India',
  'Mayank Markande': 'India',
  'Mohammad Nabi': 'Afghanistan',
  'Mohammed Shami': 'India',
  'Mohammed Siraj': 'India',
  'Mohsin Khan': 'India',
  'Mujeeb Ur Rahman': 'Afghanistan',
  'Mukesh Kumar': 'India',
  'Murugan Ashwin': 'India',
  'N Pooran': 'West Indies',
  'N Rana': 'India',
  'NLTC Perera': 'Sri Lanka',
  'NM Lyon': 'Australia',
  'NT Ellis': 'Australia',
  'Naveen-ul-Haq': 'Afghanistan',
  'Navdeep Saini': 'India',
  'Noor Ahmad': 'Afghanistan',
  'P Kumar': 'India',
  'PA Patel': 'India',
  'PD Salt': 'England',
  'PJ Cummins': 'Australia',
  'PP Chawla': 'India',
  'PP Ojha': 'India',
  'PVD Chameera': 'Sri Lanka',
  'Pawan Negi': 'India',
  'Prasidh Krishna': 'India',
  'Prithvi Shaw': 'India',
  'Q de Kock': 'South Africa',
  'R Ashwin': 'India',
  'R Dravid': 'India',
  'R Parag': 'India',
  'R Sai Kishore': 'India',
  'R Tewatia': 'India',
  'R Vinay Kumar': 'India',
  'RA Jadeja': 'India',
  'RD Chahar': 'India',
  'RD Gaikwad': 'India',
  'RE van der Merwe': 'Netherlands',
  'RG Sharma': 'India',
  'RJW Topley': 'England',
  'RL Chase': 'West Indies',
  'RP Singh': 'India',
  'RR Pant': 'India',
  'RR Rossouw': 'South Africa',
  'RT Ponting': 'Australia',
  'RV Uthappa': 'India',
  'Rachin Ravindra': 'New Zealand',
  'Rahul Chahar': 'India',
  'Rajat Patidar': 'India',
  'Rashid Khan': 'Afghanistan',
  'Ravi Bishnoi': 'India',
  'Rinku Singh': 'India',
  'S Badree': 'West Indies',
  'S Badrinath': 'India',
  'S Dhawan': 'India',
  'S Sreesanth': 'India',
  'SA Abbott': 'Australia',
  'SA Yadav': 'India',
  'SC Ganguly': 'India',
  'SE Marsh': 'Australia',
  'SK Raina': 'India',
  'SL Malinga': 'Sri Lanka',
  'SM Curran': 'England',
  'SMSM Senanayake': 'Sri Lanka',
  'SO Hetmyer': 'West Indies',
  'SP Narine': 'West Indies',
  'SPD Smith': 'Australia',
  'SR Tendulkar': 'India',
  'SR Watson': 'Australia',
  'SS Iyer': 'India',
  'SS Tiwary': 'India',
  'SV Samson': 'India',
  'SW Billings': 'England',
  'Sandeep Sharma': 'India',
  'Sarfaraz Khan': 'India',
  'Shahbaz Ahmed': 'India',
  'Shardul Thakur': 'India',
  'Shreyas Gopal': 'India',
  'Shubman Gill': 'India',
  'Simarjeet Singh': 'India',
  'Suyash Sharma': 'India',
  'T Natarajan': 'India',
  'T Shamsi': 'South Africa',
  'T Stubbs': 'South Africa',
  'TA Boult': 'New Zealand',
  'TD Paine': 'Australia',
  'TG Southee': 'New Zealand',
  'TK Curran': 'England',
  'TM Dilshan': 'Sri Lanka',
  'TM Head': 'Australia',
  'TWM Latham': 'New Zealand',
  'Tilak Varma': 'India',
  'Tushar Deshpande': 'India',
  'UT Yadav': 'India',
  'V Kohli': 'India',
  'V Sehwag': 'India',
  'V Shankar': 'India',
  'VR Iyer': 'India',
  'W Hasaranga': 'Sri Lanka',
  'WD Parnell': 'South Africa',
  'WG Jacks': 'England',
  'WP Saha': 'India',
  'Washington Sundar': 'India',
  'Y Chahal': 'India',
  'YK Pathan': 'India',
  'YS Chahal': 'India',
  'Yash Dayal': 'India',
  'Yashasvi Jaiswal': 'India',
  'Yuvraj Singh': 'India',
  'Z Khan': 'India',
}